"""Add unique constraint to ProductUser

Revision ID: 2b5ca1b781e9
Revises: c45dcdd7db71
Create Date: 2024-06-02 04:26:12.407299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5ca1b781e9'
down_revision = 'c45dcdd7db71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_product_unique', ['user_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_user', schema=None) as batch_op:
        batch_op.drop_constraint('user_product_unique', type_='unique')

    # ### end Alembic commands ###
